name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Create and publish the GDS artifact
        uses: TinyTapeout/tt-gds-action/custom_gds@tt05
        with: 
          top_module: <mag/top_module.mag> 
          gds_path: <gds/top_module.gds>
          lef_path: <lef/top_module.lef>
          verilog_path: <verilog/top_module.v>
